/**
 * @file optimization_report.ts
 * @description Compiles actionable recommendations to improve cache hit rates and DAG concurrency.
 */

import type { Wave } from "../orchestrator/planner";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface PathTask {
    id: string;
    durationMs: number;
}

export interface RefactorProposal {
    taskA: string;
    taskB: string;
    sharedClaim: string;
    reason: string;
    suggestion: string;
}

export interface ShadowSimulation {
    description: string;
    projectedSavingsMs: number;
    gainPercent: number;
}

export interface OptimizationData {
    criticalPath: PathTask[];
    wavePlan: Wave[];
    theoreticalMinMs: number;
    actualCurrentMs: number;
    proposals: RefactorProposal[];
    shadowSimulations: ShadowSimulation[];
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function fmt(ms: number): string {
    return ms.toLocaleString("en-US") + "ms";
}

// ─── Report Generator ────────────────────────────────────────────────────────

export class OptimizationReport {
    /**
     * Generate an Optimization Report in Markdown.
     */
    static generate(data: OptimizationData): string {
        const efficiency = (data.theoreticalMinMs / data.actualCurrentMs) * 100;
        const savingsMs = data.actualCurrentMs - data.theoreticalMinMs;
        const deadAirMs = savingsMs;

        const sections = [
            this.header(),
            this.velocityMetrics(data, efficiency, savingsMs, deadAirMs),
            this.criticalPathSection(data.criticalPath),
            this.waveVisualization(data.wavePlan),
        ];

        if (data.proposals.length > 0) {
            sections.push(this.refactorRoadmap(data.proposals));
        }

        if (data.shadowSimulations.length > 0) {
            sections.push(this.shadowBuild(data.shadowSimulations));
        }

        sections.push(this.footer(efficiency));

        return sections.join("\n\n");
    }

    // ── Sections ─────────────────────────────────────────────────────────

    private static header(): string {
        return `# Optimization Report\n\n_Generated by B4mal — Amdahl's Law + Critical Path Method_`;
    }

    private static velocityMetrics(
        data: OptimizationData,
        efficiency: number,
        savingsMs: number,
        deadAirMs: number,
    ): string {
        return `## Velocity Metrics

| Metric | Value |
|---|---|
| **Current Build Duration** | ${fmt(data.actualCurrentMs)} |
| **Critical Path Duration** | ${fmt(data.theoreticalMinMs)} |
| **Parallelization Efficiency** | ${efficiency.toFixed(2)}% |
| **Savings Potential** | ${fmt(savingsMs)} |
| **Dead Air (CPU Idle)** | ${fmt(deadAirMs)} |
| **Wave Count** | ${data.wavePlan.length} |`;
    }

    private static criticalPathSection(path: PathTask[]): string {
        if (path.length === 0) return "## The Critical Path\n\n_No tasks in the critical path._";

        const steps = path.map((t, i) => {
            const arrow = i < path.length - 1 ? " →" : " ■";
            return `${i + 1}. **${t.id}** — ${fmt(t.durationMs)}${arrow}`;
        });

        return `## The Critical Path (The "Longest Pole")

${steps.join("\n")}

> The critical path determines the **minimum possible build time**.
> No amount of parallelization can reduce wall-clock time below **${fmt(path.reduce((s, t) => s + t.durationMs, 0))}**.`;
    }

    private static waveVisualization(waves: Wave[]): string {
        if (waves.length === 0) return "## Wave Plan\n\n_No waves planned._";

        const rows = waves.map(w => {
            const tasks = w.taskIds.join(", ");
            const parallel = w.taskIds.length;
            return `| Wave ${w.depth} | ${parallel} | ${tasks} |`;
        });

        return `## Wave Execution Plan

| Wave | Parallelism | Tasks |
|---|---|---|
${rows.join("\n")}`;
    }

    private static refactorRoadmap(proposals: RefactorProposal[]): string {
        const items = proposals.map((p, i) => {
            return `### ${i + 1}. ${p.taskA} ↔ ${p.taskB}

- **Shared Claim:** \`${p.sharedClaim}\`
- **Reason:** ${p.reason}
- **Suggestion:** ${p.suggestion}`;
        });

        return `## Refactor Roadmap

${items.join("\n\n")}`;
    }

    private static shadowBuild(simulations: ShadowSimulation[]): string {
        const items = simulations.map(s => {
            return `- ${s.description}: **${fmt(s.projectedSavingsMs)}** savings (**${s.gainPercent}%** gain)`;
        });

        return `## Build Simulations

_Projected impact of resource isolation changes._

${items.join("\n")}`;
    }

    private static footer(efficiency: number): string {
        const grade = efficiency >= 90 ? "A+" :
            efficiency >= 80 ? "A" :
                efficiency >= 70 ? "B" :
                    efficiency >= 50 ? "C" : "D";

        return `---

**Grade: ${grade}** | Efficiency: ${efficiency.toFixed(2)}%`;
    }
}
