import { describe, expect, test, beforeAll, afterAll } from "bun:test";
import { CIEmitter } from "../src/shim/ci_emitter";
import * as fs from "fs";
import * as path from "path";

describe("CIEmitter (GitHub Actions)", () => {
    const testDir = path.join(process.cwd(), "tests/fixtures/ci_emitter");

    beforeAll(() => {
        fs.mkdirSync(testDir, { recursive: true });
    });

    afterAll(() => {
        fs.rmSync(testDir, { recursive: true, force: true });
    });

    test("generates valid GitHub Actions YAML structure", () => {
        const yaml = CIEmitter.emitGithubActions();
        
        // Basic workflow assertions
        expect(yaml).toContain("name: B4mal CI");
        expect(yaml).toContain("on:");
        expect(yaml).toContain("push:");
        expect(yaml).toContain("pull_request:");
        expect(yaml).toContain("workflow_dispatch:");
        
        // Security permissions
        expect(yaml).toContain("permissions: read-all");
        
        // Job structure assertions
        expect(yaml).toContain("jobs:");
        expect(yaml).toContain("build:");
        expect(yaml).toContain("runs-on: ubuntu-latest");
        
        // Concurrency
        expect(yaml).toContain("concurrency:");
        expect(yaml).toContain("cancel-in-progress: ${{ github.event_name == 'pull_request' }}");
        
        // Step assertions
        expect(yaml).toContain("uses: actions/checkout@v4");
        expect(yaml).toContain("b4mal build");
    });

    test("injects actions/cache for zero-config global remote caching", () => {
        const yaml = CIEmitter.emitGithubActions();
        
        expect(yaml).toContain("uses: actions/cache@v4");
        expect(yaml).toContain("path: .b4mal/");
        // The cache key uses the lockfile, dropping github.sha to avoid the 10GB limit thrashing trap
        expect(yaml).toContain("key: ${{ runner.os }}-b4mal-${{ hashFiles('**/b4mal.lock') }}");
        expect(yaml).toContain("restore-keys:");
        expect(yaml).toContain("${{ runner.os }}-b4mal-");
    });

    test("includes B4mal installation step pinned to a version", () => {
        const yaml = CIEmitter.emitGithubActions();
        expect(yaml).toContain("Install B4mal");
        // Pin global installations to prevent supply chain attacks
        // It should match semver or a valid tag, we test it doesn't just use @latest
        expect(yaml).toMatch(/npm i -g @bneb\/b4mal@\d+\.\d+\.\d+/);
    });

    test("infers toolchains based on directory contents (Node.js)", () => {
        const pkgPath = path.join(testDir, "package.json");
        fs.writeFileSync(pkgPath, '{"name": "test"}');
        
        const yaml = CIEmitter.emitGithubActions({ cwd: testDir });
        expect(yaml).toContain("uses: actions/setup-node@v4");
        // Should not inject npm ci if no lockfile
        expect(yaml).not.toContain("run: npm ci");
        
        fs.rmSync(pkgPath);
    });

    test("injects npm ci when package-lock.json is present", () => {
        const pkgPath = path.join(testDir, "package.json");
        const lockPath = path.join(testDir, "package-lock.json");
        fs.writeFileSync(pkgPath, '{"name": "test"}');
        fs.writeFileSync(lockPath, '{"name": "test"}');
        
        const yaml = CIEmitter.emitGithubActions({ cwd: testDir });
        expect(yaml).toContain("uses: actions/setup-node@v4");
        expect(yaml).toContain("npm ci");
        
        fs.rmSync(pkgPath);
        fs.rmSync(lockPath);
    });

    test("includes commented out deployment permissions", () => {
        const yaml = CIEmitter.emitGithubActions();
        expect(yaml).toContain("permissions: read-all");
        expect(yaml).toContain("# contents: write");
        expect(yaml).toContain("# id-token: write");
    });

    test("infers toolchains based on directory contents (Rust)", () => {
        // Mock a Cargo.toml existing
        const cargoPath = path.join(testDir, "Cargo.toml");
        fs.writeFileSync(cargoPath, '[package]\nname="test"');

        const yaml = CIEmitter.emitGithubActions({ cwd: testDir });
        expect(yaml).toContain("uses: dtolnay/rust-toolchain@stable");

        fs.rmSync(cargoPath);
    });

    test("falls back to latest when package.json cannot be read", () => {
        const yaml = CIEmitter.emitGithubActions();
        expect(yaml).toContain("npm i -g @bneb/b4mal@");
    });
});

// ─── GitLab CI ─────────────────────────────────────────────────────────────

describe("CIEmitter (GitLab CI)", () => {
    test("generates valid GitLab CI YAML structure", () => {
        const yaml = CIEmitter.emitGitLabCI();

        expect(yaml).toContain("Auto-generated by B4mal");
        expect(yaml).toContain("stages:");
        expect(yaml).toContain("build");
        expect(yaml).toContain("b4mal-build:");
        expect(yaml).toContain("image: oven/bun");
        expect(yaml).toContain("bun x b4mal build");
        expect(yaml).toContain("cache:");
        expect(yaml).toContain("b4mal.lock");
    });

    test("includes node toolchain steps when package.json present", () => {
        const dir = path.join(process.cwd(), "tests/fixtures/ci_emitter");
        const pkgPath = path.join(dir, "package.json");
        const lockPath = path.join(dir, "package-lock.json");
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(pkgPath, '{"name": "test"}');
        fs.writeFileSync(lockPath, '{"name": "test"}');

        const yaml = CIEmitter.emitGitLabCI({ cwd: dir });
        expect(yaml).toContain("before_script:");
        expect(yaml).toContain("npm ci");

        fs.rmSync(pkgPath);
        fs.rmSync(lockPath);
    });
});

// ─── CircleCI ───────────────────────────────────────────────────────────────

describe("CIEmitter (CircleCI)", () => {
    test("generates valid CircleCI YAML structure", () => {
        const yaml = CIEmitter.emitCircleCI();

        expect(yaml).toContain("Auto-generated by B4mal");
        expect(yaml).toContain("version: 2.1");
        expect(yaml).toContain("jobs:");
        expect(yaml).toContain("b4mal-build:");
        expect(yaml).toContain("image: oven/bun");
        expect(yaml).toContain("bun x b4mal build");
        expect(yaml).toContain("restore_cache:");
        expect(yaml).toContain("save_cache:");
        expect(yaml).toContain("workflows:");
    });

    test("includes install step when node toolchain detected", () => {
        const dir = path.join(process.cwd(), "tests/fixtures/ci_emitter");
        const pkgPath = path.join(dir, "package.json");
        const lockPath = path.join(dir, "package-lock.json");
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(pkgPath, '{"name": "test"}');
        fs.writeFileSync(lockPath, '{"name": "test"}');

        const yaml = CIEmitter.emitCircleCI({ cwd: dir });
        expect(yaml).toContain("npm ci");

        fs.rmSync(pkgPath);
        fs.rmSync(lockPath);
    });
});

// ─── Buildkite ──────────────────────────────────────────────────────────────

describe("CIEmitter (Buildkite)", () => {
    test("generates valid Buildkite YAML structure", () => {
        const yaml = CIEmitter.emitBuildkite();

        expect(yaml).toContain("Auto-generated by B4mal");
        expect(yaml).toContain("steps:");
        expect(yaml).toContain("B4mal Build");
        expect(yaml).toContain("bun x b4mal build");
        expect(yaml).toContain("concurrency: 1");
        expect(yaml).toContain("concurrency_group: b4mal-build");
    });

    test("includes npm ci when package-lock.json present", () => {
        const dir = path.join(process.cwd(), "tests/fixtures/ci_emitter");
        const pkgPath = path.join(dir, "package.json");
        const lockPath = path.join(dir, "package-lock.json");
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(pkgPath, '{"name": "test"}');
        fs.writeFileSync(lockPath, '{"name": "test"}');

        const yaml = CIEmitter.emitBuildkite({ cwd: dir });
        expect(yaml).toContain("npm ci");

        fs.rmSync(pkgPath);
        fs.rmSync(lockPath);
    });
});

// ─── Bitbucket ──────────────────────────────────────────────────────────────

describe("CIEmitter (Bitbucket)", () => {
    test("generates valid Bitbucket YAML structure", () => {
        const yaml = CIEmitter.emitBitbucket();

        expect(yaml).toContain("Auto-generated by B4mal");
        expect(yaml).toContain("image: oven/bun");
        expect(yaml).toContain("pipelines:");
        expect(yaml).toContain("B4mal Build");
        expect(yaml).toContain("bun x b4mal build");
        expect(yaml).toContain("caches:");
        expect(yaml).toContain("b4mal");
        expect(yaml).toContain("definitions:");
    });

    test("includes script steps when node toolchain detected", () => {
        const dir = path.join(process.cwd(), "tests/fixtures/ci_emitter");
        const pkgPath = path.join(dir, "package.json");
        const lockPath = path.join(dir, "package-lock.json");
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(pkgPath, '{"name": "test"}');
        fs.writeFileSync(lockPath, '{"name": "test"}');

        const yaml = CIEmitter.emitBitbucket({ cwd: dir });
        expect(yaml).toContain("script:");
        expect(yaml).toContain("npm ci");

        fs.rmSync(pkgPath);
        fs.rmSync(lockPath);
    });
});
