import * as fs from "fs";
import * as path from "path";

export interface CIEmitterOptions {
    cwd?: string;
}

export type CITarget = "github" | "gitlab" | "circleci" | "buildkite" | "bitbucket";

interface ToolchainInfo {
  hasNode: boolean;
  hasPackageLock: boolean;
  hasRust: boolean;
}

// ─── Shared helpers ─────────────────────────────────────────────────────

function resolveB4malVersion(): string {
  try {
    const pkgPath = path.join(__dirname, "../../package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
    return pkg.version ?? "latest";
  } catch {
    return "latest";
  }
}

function githubToolchainSteps(ti: ToolchainInfo): string {
  let steps = "";
  if (ti.hasNode) steps += `
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'`;
  if (ti.hasRust) steps += `
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable`;
  return steps;
}

function depsCommand(ti: ToolchainInfo): string {
  return ti.hasPackageLock ? "npm ci" : 'echo "Please ensure dependencies are installed"';
}

function githubJobBody(toolchain: string, deps: string, version: string): string {
  return `
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
${toolchain}
      - name: Install Dependencies
        run: |
          ${deps}

      - name: Install B4mal
        run: npm i -g b4mal@${version}

      - name: Restore B4mal Global Cache
        uses: actions/cache@v4
        with:
          path: .b4mal/
          key: \${{ runner.os }}-b4mal-\${{ hashFiles('**/b4mal.lock') }}
          restore-keys: |
            \${{ runner.os }}-b4mal-

      - name: Execute Verified DAG
        run: b4mal build
`;
}

// ─── Emitters ───────────────────────────────────────────────────────────

export class CIEmitter {
    static emitGithubActions(options: CIEmitterOptions = {}): string {
        const ti = this.detectToolchains(options);
        const toolchain = githubToolchainSteps(ti);
        const deps = depsCommand(ti);
        const version = resolveB4malVersion();
        return `name: B4mal CI

# Auto-generated by B4mal (The CI Emitter)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: \${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: B4mal Orchestrator
    runs-on: ubuntu-latest
${githubJobBody(toolchain, deps, version)}
`;
    }

    static emitGitLabCI(options: CIEmitterOptions = {}): string {
      const ti = this.detectToolchains(options);
      return `# Auto-generated by B4mal
stages:
  - build

variables:
  BUN_VERSION: "1.2"

b4mal-build:
  stage: build
  image: oven/bun:\${BUN_VERSION}
  cache:
    key:
      files:
        - b4mal.lock
      prefix: b4mal
    paths:
      - .b4mal/
  interruptible: true
${ti.hasNode ? `
  before_script:
    - ${ti.hasPackageLock ? "npm ci" : "bun install"}
` : ""}
  script:
    - bun x b4mal build
  rules:
    - if: \$CI_COMMIT_BRANCH == "main" || \$CI_PIPELINE_SOURCE == "merge_request_event"
`;
    }

    static emitCircleCI(options: CIEmitterOptions = {}): string {
      const ti = this.detectToolchains(options);
      const installStep = ti.hasNode
        ? `\n      - run:\n          name: Install Dependencies\n          command: ${ti.hasPackageLock ? "npm ci" : "bun install"}\n`
        : "";
      return `# Auto-generated by B4mal
version: 2.1

jobs:
  b4mal-build:
    docker:
      - image: oven/bun:1.2
    steps:
      - checkout${installStep}
      - restore_cache:
          keys:
            - b4mal-v1-{{ .Branch }}-{{ checksum "b4mal.lock" }}
            - b4mal-v1-{{ .Branch }}-
      - run:
          name: Execute Verified DAG
          command: bun x b4mal build
      - save_cache:
          key: b4mal-v1-{{ .Branch }}-{{ checksum "b4mal.lock" }}
          paths:
            - .b4mal/

workflows:
  build:
    jobs:
      - b4mal-build
`;
    }

    static emitBuildkite(options: CIEmitterOptions = {}): string {
      const ti = this.detectToolchains(options);
      return `# Auto-generated by B4mal
steps:
  - label: "B4mal Build"
    command: |
      ${ti.hasNode ? `${ti.hasPackageLock ? "npm ci" : "bun install"}\n      ` : ""}bun x b4mal build
    concurrency: 1
    concurrency_group: b4mal-build
    plugins:
      - cache#v2:
          manifest: b4mal.lock
          path: .b4mal/
    agents:
      queue: default
`;
    }

    static emitBitbucket(options: CIEmitterOptions = {}): string {
      const ti = this.detectToolchains(options);
      return `# Auto-generated by B4mal
image: oven/bun:1.2

pipelines:
  default:
    - step:
        name: B4mal Build
        caches:
          - b4mal
${ti.hasNode ? `
        script:
          - ${ti.hasPackageLock ? "npm ci" : "bun install"}
          - bun x b4mal build
` : `
        script:
          - bun x b4mal build
`}
definitions:
  caches:
    b4mal: .b4mal/
`;
    }

    private static detectToolchains(options: CIEmitterOptions): ToolchainInfo {
      const cwd = options.cwd || process.cwd();
      return {
        hasNode: fs.existsSync(path.join(cwd, "package.json")),
        hasPackageLock: fs.existsSync(path.join(cwd, "package-lock.json")),
        hasRust: fs.existsSync(path.join(cwd, "Cargo.toml")) || fs.existsSync(path.join(cwd, "Cargo.lock")),
      };
    }
}
