import * as fs from "fs";
import * as path from "path";

export interface CIEmitterOptions {
    cwd?: string;
}

export class CIEmitter {
    /**
     * Emit a natively optimized GitHub Actions workflow for B4mal.
     * Uses a single VM to preserve B4mal's formal verification and local multi-process execution speed.
     * Leverages actions/cache for zero-config global remote caching.
     */
    static emitGithubActions(options: CIEmitterOptions = {}): string {
        const cwd = options.cwd || process.cwd();
        
        let b4malVersion = "latest";
        try {
            const pkgPath = path.join(__dirname, "../../package.json");
            const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
            if (pkg.version) b4malVersion = pkg.version;
        } catch (e) {
            // fallback
        }

        // Infer toolchains
        const hasNode = fs.existsSync(path.join(cwd, "package.json"));
        const hasPackageLock = fs.existsSync(path.join(cwd, "package-lock.json"));
        const hasRust = fs.existsSync(path.join(cwd, "Cargo.toml")) || fs.existsSync(path.join(cwd, "Cargo.lock"));

        let toolchainSteps = "";

        if (hasNode) {
            toolchainSteps += `
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'`;
        }

        if (hasRust) {
            toolchainSteps += `
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable`;
        }

        return `name: B4mal CI

# Auto-generated by B4mal (The CI Emitter)
# 
# This workflow runs your entire DAG natively on a single VM.
# B4mal's internal WavePlanner handles multi-process concurrency,
# completely avoiding GHA VM provisioning limits and artifact network latency.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all
# Uncomment these if your DAG requires publishing to registries or cloud providers
# contents: write
# id-token: write
# packages: write

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: \${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: B4mal Orchestrator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
${toolchainSteps}
      - name: Install Dependencies
        run: |
          # B4mal automatically orchestrates your build, but if your DAG doesn't include an install step,
          # do it here (e.g. npm ci, bun install, cargo fetch)
          ${hasPackageLock ? "npm ci" : 'echo "Please ensure dependencies are installed"'}

      - name: Install B4mal
        run: npm i -g b4mal@${b4malVersion}

      - name: Restore B4mal Global Cache
        uses: actions/cache@v4
        with:
          path: .b4mal/
          key: \${{ runner.os }}-b4mal-\${{ hashFiles('**/b4mal.lock') }}
          restore-keys: |
            \${{ runner.os }}-b4mal-

      - name: Execute Verified DAG
        run: b4mal build
`;
    }
}
