import { EbpfTracer } from "../trace/ebpf_linux";
import { EventAggregator } from "../trace/aggregator";
import { GraphSynthesizer } from "../trace/synthesizer";
import { platform } from "os";

export class TraceCommand {
    static async execute(args: string[]) {
        if (args.length === 0) {
            console.error("Usage: b4mal trace <command...>");
            process.exit(1);
        }
        
        const cmd = args.join(" ");
        console.log(`\x1b[36m[b4mal]\x1b[0m Autonomous Trace Synthesis (eBPF mode): \x1b[1m${cmd}\x1b[0m`);
        
        if (platform() !== "linux") {
            console.warn(`\x1b[33mWarning: eBPF tracing is designed for Linux. Running on ${platform()} may fail or fallback to user-space trace.\x1b[0m`);
        }

        const tracer = new EbpfTracer();
        let events;
        try {
            console.log(`\x1b[90mStarting trace (this requires 'strace' or root privileges)...\x1b[0m`);
            events = await tracer.trace(cmd);
        } catch (e) {
            console.error(`\x1b[31mTrace failed:\x1b[0m ${e}`);
            process.exit(1);
        }

        console.log(`\x1b[32m✔\x1b[0m Captured ${events.length} trace events.`);

        const aggregator = new EventAggregator();
        for (const event of events) {
            aggregator.processEvent(event);
        }

        const nodes = aggregator.getNodes();
        const synthesizer = new GraphSynthesizer();
        const pipeline = synthesizer.synthesize(nodes, cmd);

        const outPath = `${process.cwd()}/b4mal_synthesized.ts`;
        const content = `// Auto-generated by b4mal trace\nimport type { Pipeline } from "./src/schema";\n\nexport default ${JSON.stringify(pipeline, null, 4)} as Pipeline;\n`;
        await Bun.write(outPath, content);
        
        console.log(`\x1b[32m✔\x1b[0m Synthesized DAG with ${pipeline.tasks.length} tasks into: \x1b[1mb4mal_synthesized.ts\x1b[0m\n`);
    }
}
