name: B4mal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: B4mal Orchestrator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest


      - name: Install Dependencies
        run: bun install

      - name: Full Test Suite
        run: bun test

      - name: Execute Verified DAG
        run: bun src/cli/index.ts build
